// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace backend.Models;

[Index("Persona_idPersona", Name = "IX_Direccion_Persona")]
[Index("idTipo_Direccion", Name = "IX_Direccion_Tipo")]
public partial class Direccion
{
    [Key]
    public int idDireccion { get; set; }

    public int idTipo_Direccion { get; set; }

    public int Persona_idPersona { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string Detalle_Direccion { get; set; }

    [JsonIgnore]
    [ForeignKey("Persona_idPersona")]
    [InverseProperty("Direccion")]
    public virtual Persona Persona_idPersonaNavigation { get; set; }

    [ForeignKey("idTipo_Direccion")]
    [InverseProperty("Direccion")]
    public virtual Tipo_Direccion idTipo_DireccionNavigation { get; set; }
}