// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace backend.Models;

[Index("Persona_idPersona", Name = "IX_Email_Persona")]
[Index("Tipo_Email_idTipo_Email", Name = "IX_Email_Tipo")]
public partial class Email
{
    [Key]
    [StringLength(200)]
    [Unicode(false)]
    public string Direccion_Email { get; set; }

    public bool? Activo { get; set; }

    public bool? Verificado { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Fecha_Creacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Fecha_Actualizacion { get; set; }

    public int Tipo_Email_idTipo_Email { get; set; }

    public int Persona_idPersona { get; set; }

    [JsonIgnore]
    [ForeignKey("Persona_idPersona")]
    [InverseProperty("Email")]
    public virtual Persona Persona_idPersonaNavigation { get; set; }

    [ForeignKey("Tipo_Email_idTipo_Email")]
    [InverseProperty("Email")]
    public virtual Tipo_Email Tipo_Email_idTipo_EmailNavigation { get; set; }
}