// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace backend.Models;

public partial class lastprojectContext : DbContext
{
    public lastprojectContext()
    {
    }

    public lastprojectContext(DbContextOptions<lastprojectContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Direccion> Direccion { get; set; }

    public virtual DbSet<Email> Email { get; set; }

    public virtual DbSet<Persona> Persona { get; set; }

    public virtual DbSet<Telefono> Telefono { get; set; }

    public virtual DbSet<Tipo_Direccion> Tipo_Direccion { get; set; }

    public virtual DbSet<Tipo_Email> Tipo_Email { get; set; }

    public virtual DbSet<Tipo_Telefono> Tipo_Telefono { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=server.asralabs.com,14330;Initial Catalog=lastproject;Persist Security Info=True;User ID=sa;Password=19861997.Sr;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Direccion>(entity =>
        {
            entity.HasKey(e => e.idDireccion).HasName("PK__Direccio__B49878C9096937E4");

            entity.HasOne(d => d.Persona_idPersonaNavigation).WithMany(p => p.Direccion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Direccion__Perso__693CA210");

            entity.HasOne(d => d.idTipo_DireccionNavigation).WithMany(p => p.Direccion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Direccion__idTip__68487DD7");
        });

        modelBuilder.Entity<Email>(entity =>
        {
            entity.HasKey(e => e.Direccion_Email).HasName("PK__Email__3F23B592B8E5E2BA");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Fecha_Actualizacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Fecha_Creacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Verificado).HasDefaultValue(false);

            entity.HasOne(d => d.Persona_idPersonaNavigation).WithMany(p => p.Email)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Email__Persona_i__5FB337D6");

            entity.HasOne(d => d.Tipo_Email_idTipo_EmailNavigation).WithMany(p => p.Email)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Email__Tipo_Emai__5EBF139D");
        });

        modelBuilder.Entity<Persona>(entity =>
        {
            entity.HasKey(e => e.idPersona).HasName("PK__Persona__A4788141D69A8883");
        });

        modelBuilder.Entity<Telefono>(entity =>
        {
            entity.HasKey(e => e.idTelefono).HasName("PK__Telefono__39C142DF2D3F8048");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Fecha_Registro).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Persona_idPersonaNavigation).WithMany(p => p.Telefono)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Telefono__Person__6477ECF3");

            entity.HasOne(d => d.Telefono_Tipo_idTelefonol_TipoNavigation).WithMany(p => p.Telefono)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Telefono__Telefo__656C112C");
        });

        modelBuilder.Entity<Tipo_Direccion>(entity =>
        {
            entity.HasKey(e => e.idTipo_Direccion).HasName("PK__Tipo_Dir__5B9EB980334C75A9");

            entity.Property(e => e.Activo).HasDefaultValue(true);
        });

        modelBuilder.Entity<Tipo_Email>(entity =>
        {
            entity.HasKey(e => e.idTipo_Email).HasName("PK__Tipo_Ema__F9D7ACD4F347DB83");

            entity.Property(e => e.Activo).HasDefaultValue(true);
        });

        modelBuilder.Entity<Tipo_Telefono>(entity =>
        {
            entity.HasKey(e => e.idTelefono_Tipo).HasName("PK__Tipo_Tel__D0D3B0BF0ABD08C6");

            entity.Property(e => e.Activo).HasDefaultValue(true);
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.idUsuario).HasName("PK__Usuario__645723A6AE9B599B");

            entity.Property(e => e.Fecha_Actualizacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Fecha_Creacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.estado).HasDefaultValue((byte)1);

            entity.HasOne(d => d.Persona_idPersonaNavigation).WithMany(p => p.Usuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Usuario__Persona__5812160E");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}