// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace backend.Models;

[Index("Persona_idPersona", Name = "IX_Telefono_Persona")]
[Index("Telefono_Tipo_idTelefonol_Tipo", Name = "IX_Telefono_Tipo")]
public partial class Telefono
{
    [Key]
    public int idTelefono { get; set; }

    public bool? Activo { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string Numero { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Fecha_Registro { get; set; }

    public int Persona_idPersona { get; set; }

    public int Telefono_Tipo_idTelefonol_Tipo { get; set; }

    [JsonIgnore]
    [ForeignKey("Persona_idPersona")]
    [InverseProperty("Telefono")]
    public virtual Persona Persona_idPersonaNavigation { get; set; }

    [ForeignKey("Telefono_Tipo_idTelefonol_Tipo")]
    [InverseProperty("Telefono")]
    public virtual Tipo_Telefono Telefono_Tipo_idTelefonol_TipoNavigation { get; set; }
}