// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace backend.Models;

public partial class Tipo_Email
{
    [Key]
    public int idTipo_Email { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string Descripcion_Tipo_Email { get; set; }

    public bool? Activo { get; set; }

    [JsonIgnore]
    [InverseProperty("Tipo_Email_idTipo_EmailNavigation")]
    public virtual ICollection<Email> Email { get; set; } = new List<Email>();
}