// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend.Models;

public partial class Tipo_Telefono
{
    [Key]
    public int idTelefono_Tipo { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string Descripcion_Telefono { get; set; }

    public bool? Activo { get; set; }

    [InverseProperty("Telefono_Tipo_idTelefonol_TipoNavigation")]
    public virtual ICollection<Telefono> Telefono { get; set; } = new List<Telefono>();
}