// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend.Models;

public partial class Tipo_Direccion
{
    [Key]
    public int idTipo_Direccion { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string Descripcion_Tipo_Direccion { get; set; }

    public bool? Activo { get; set; }

    [InverseProperty("idTipo_DireccionNavigation")]
    public virtual ICollection<Direccion> Direccion { get; set; } = new List<Direccion>();
}