// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend.Models;

[Index("Persona_idPersona", Name = "IX_Usuario_Persona")]
public partial class Usuario
{
    [Key]
    [StringLength(45)]
    [Unicode(false)]
    public string idUsuario { get; set; }

    public byte estado { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Clave { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Fecha_Creacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Fecha_Actualizacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Fecha_Ultimo_Inicio { get; set; }

    public int Persona_idPersona { get; set; }

    [ForeignKey("Persona_idPersona")]
    [InverseProperty("Usuario")]
    public virtual Persona Persona_idPersonaNavigation { get; set; }
}